# Generated by Django 5.0.7 on 2024-08-05 11:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_notes_options_homewok'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Homewok',
            new_name='Homework',
        ),
    ]
